name: notification
description: "Notification Feature"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  base:
    path: ../../core/base
  assets:
    path: ../../core/assets
  ui:
    path: ../../core/ui
  localization:
    path: ../../core/localization
  domain:
    path: ../../core/domain
  debug:
    path: ../../core/debug
  questionnaire_kit:
    path: ../../common/questionnaire_kit

  carousel_slider: ^5.0.0
  flutter_screenutil: ^5.9.3
  formz: ^0.7.0
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.5
  shimmer: ^3.0.0
  zoom_tap_animation: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.2.6
  flutter_reaction_button: ^3.0.0+3
  share_plus: ^7.0.2
  video_thumbnail:
    git:
      url: https://github.com/toe-lie/video_thumbnail.git
      ref: master
  youtube_player_flutter: ^9.0.3
  path_provider: ^2.0.15
  expandable_page_view: ^1.0.17
  flip_card: ^0.7.0
  timeago: ^3.7.0
  pull_to_refresh: ^2.0.0
  html_unescape: ^2.0.0

dependency_overrides:
  web: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  bloc_test: ^9.1.3
  mocktail: ^0.3.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
