name: drift_database
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

scripts:
  build_runner_build: dart run build_runner build --delete-conflicting-outputs
  build_runner_watch: dart run build_runner watch --delete-conflicting-outputs
  drift_analyze: dart run drift_dev analyze
  drift_identify: dart run drift_dev identify-databases
  drift_bump_schema: dart run drift_dev schema dump lib/src/drift_mtp_database.dart schemas/drift_schema_v2.json
  drift_generate_migration_steps: dart run drift_dev schema steps schemas/ lib/src/schema_versions.dart
  drift_generate_migration_test: dart run drift_dev schema generate schemas/ test/generated_migrations/
  drift generate_test_companions: dart run drift_dev schema generate --data-classes --companions schemas/ test/generated/

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  base:
    path: ../../core/base
  preferences:
    path: ../../core/preferences
  database:
    path: ../../core/database
  domain:
    path: ../../core/domain
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  drift_dev: ^2.21.2
  sqlite3_flutter_libs: ^0.5.26
  path_provider: ^2.0.15
  path: ^1.8.3
  rxdart: ^0.27.7

dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  test: ^1.24.1
  mocktail: ^0.3.0
  build_runner: ^2.4.11

