name: mtp_flutter

packages:
  - packages/*
  - packages/*/*
  - packages/*/*/*
  - tests

ide:
  intellij: true

command:
  bootstrap:
    environment:
      sdk: '>=3.0.1 <4.0.0'
      flutter: ">=3.0.0 <4.0.0"
    dependencies:
      animated_toggle_switch: ^0.8.2
      bloc: ^8.1.2
      bloc_concurrency: ^0.2.5
      carousel_slider: ^5.0.0
      chewie: ^1.8.1
      chucker_flutter: ^1.5.2
      collection: ^1.17.1
      connectivity_plus: ^6.0.3
      decimal: ^2.3.2
      dio: ^5.4.2+1
      drift: ^2.21.0
      drift_dev: ^2.21.2
      drift_flutter: ^0.2.1
      drift_db_viewer: ^2.0.0
      dropdown_button2: ^2.3.9
      equatable: ^2.0.5
      firebase_analytics: ^11.3.5
      firebase_core: ^3.6.0
      firebase_messaging: ^15.1.5
      flutter:
        sdk: flutter
      flutter_bloc: ^8.1.3
      flutter_driver:
        sdk: flutter
      flutter_inappwebview: ^6.1.2
      flutter_layout_grid: ^2.0.0
      flutter_reaction_button: ^3.0.0+3
      flutter_staggered_grid_view: ^0.7.0
      flutter_widget_from_html: ^0.15.2
      flutter_widget_from_html_core: ^0.15.2
      formz: ^0.7.0
      go_router: ^14.1.3
      google_fonts: ^5.1.0
      hive: ^2.2.3
      hive_flutter: ^1.1.0
      internet_connection_checker: ^1.0.0+1
      intl: ^0.19.0
      intl_phone_field: ^3.2.0
      json_annotation: ^4.8.1
      jwt_decoder: ^2.0.1
      lottie: ^2.7.0
      path: ^1.8.3
      path_provider: ^2.0.15
      photo_view: ^0.15.0
      pinput: ^4.0.0
      responsive_framework: ^1.4.0
      rxdart: ^0.27.7
      share_plus: ^7.0.2
      shimmer: ^3.0.0
      smooth_page_indicator: ^1.1.0
      sqlite3_flutter_libs: ^0.5.26
      timeago: ^3.7.0
      url_launcher: ^6.2.6
      uuid: ^4.0.0
      video_player: ^2.8.6
      video_thumbnail:
        git:
          url: https://github.com/toe-lie/video_thumbnail.git
          ref: master
      workmanager: ^0.5.2
      youtube_player_flutter: ^9.0.3
      zoom_tap_animation: ^1.1.0

    dev_dependencies:
      flutter_lints: ^3.0.2
      build_runner: ^2.4.11

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    run: |
      melos exec -c 1 -- \
        flutter analyze --fatal-infos
    parallel: true
    description: Run `flutter analyze` for all packages.

  format:
    run: melos exec dart format . --fix
    description: Run `dart format` for all packages.

  format-check:
    run: melos exec dart format . --set-exit-if-changed
    description: Run `dart format` checks for all packages.

  gen:build_runner:select:
    run: melos exec dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner for all packages.
    packageFilters:
      dependsOn: [ build_runner ]

  gen:build_runner:
    run: melos run gen:build_runner:select --no-select
    description: Run build_runner for all packages.

  test:select:
    run: melos exec -c 1 -- flutter test
    packageFilters:
      dirExists: test
    description: Run `flutter test` for selected packages.

  test:
    run: melos run test:select --no-select
    description: Run all Flutter tests in this project.

  get:
    description: Get packages in a Flutter project.
    run: melos exec dart pub get flutter pub get

  get:dart:
    description: Get packages in a Dart project.
    run: melos exec dart pub get

  run:build_runner:
    description: Run build_runner in the project.
    run: dart run build_runner build --delete-conflicting-outputs