name: mtp
description: MTP Flutter Project
publish_to: 'none'
version: 3.0.1+71

scripts:
  build_runner_build: dart run build_runner build --delete-conflicting-outputs
  build_runner_watch: dart run build_runner watch --delete-conflicting-outputs
  create_feature_package: flutter create --template=package /packages/features/{package_name}
  create_core_flutter_package: flutter create --template=package /packages/features/{package_name}
  create_core_dart_package: dart create -t package /packages/impl/retrofit_api
  generate_assets: fluttergen -c ./packages/core/assets/pubspec.yaml
  sync_localization:
    script: excel2arb -u https://shorturl.at/lqQV9 -o lib/l10n/locales -g true
    description: Sync localization files from google sheet
    directory: packages/core/localization

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  chucker_flutter: ^1.5.2
  decimal: ^2.3.2
  dio: ^5.4.2+1
  drift_db_viewer: ^2.0.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_driver:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.1.3
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  lottie: ^2.7.0
  path: ^1.8.3
  path_provider: ^2.0.15
  responsive_framework: ^1.4.0
  rxdart: ^0.27.7
  smooth_page_indicator: ^1.1.0
  flutter_localized_locales: ^2.0.5
  flutter_inappwebview: ^6.1.2
  app_links: ^6.3.2
  firebase_analytics: ^11.3.5
  timezone: ^0.9.0
  flutter_native_splash: ^2.4.3

  base:
    path: packages/core/base
  data:
    path: packages/core/data
  domain:
    path: packages/core/domain
  design_system:
    path: packages/core/design_system
  ui:
    path: packages/core/ui
  api:
    path: packages/core/api
  localization:
    path: packages/core/localization
  assets:
    path: packages/core/assets
  flavor:
    path: packages/core/flavor
  preferences:
    path: packages/core/preferences
  database:
    path: packages/core/database
  messaging:
    path: packages/core/messaging
  analytics:
    path: packages/core/analytics

  offline_cache:
    path: packages/common/offline_cache
  file_downloader:
    path: packages/common/file_downloader

  hive_preferences:
    path: packages/impl/hive_preferences
  retrofit_api:
    path: packages/impl/retrofit_api
  drift_database:
    path: packages/impl/drift_database

  debug:
    path: packages/core/debug

  auth:
    path: packages/features/auth
  home:
    path: packages/features/home
  learning:
    path: packages/features/learning
  blog:
    path: packages/features/blog
  profile:
    path: packages/features/profile
  help:
    path: packages/features/help
  settings:
    path: packages/features/settings
  e_library:
    path: packages/features/e_library
  notification:
    path: packages/features/notification
  thematic_group:
    path: packages/features/thematic_group
  subscription:
    path: packages/features/subscription
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  test: ^1.24.1
  mocktail: ^1.0.4
  bloc_test: ^9.1.3
  melos: ^6.1.0
  json_serializable: ^6.7.0
  go_router_builder: any
  build_runner: any
  build_verify: any
  flutter_gen_runner: any

flutter_native_splash:
  android: true
  ios: true
  background_image: "assets/images/splash.jpg"
  android_12:
    background_image: "assets/images/splash.jpg"

dependency_overrides:
  file: 7.0.0
  process: 5.0.1
  carousel_slider: 5.0.0
  flutter_local_notifications: 17.2.2
  web: ^1.0.0
  photo_view: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Pyidaungsu
      fonts:
        - asset: packages/assets/fonts/Pyidaungsu-Regular.ttf
          weight: 400
        - asset: packages/assets/fonts/Pyidaungsu-Bold.ttf
          weight: 500
        - asset: packages/assets/fonts/Pyidaungsu-Bold.ttf
          weight: 600
        - asset: packages/assets/fonts/Pyidaungsu-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: packages/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: packages/assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: packages/assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: packages/assets/fonts/Inter-Bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
