import 'package:database/database.dart';
import 'package:drift_database/drift_database.dart';

extension CourseEntryEntityMapper on CourseEntry {
  CourseEntity toEntity({
    required CourseLearnerEntity? courseLearner,
    required List<LectureEntity> lectures,
    required List<LearningActivityEntity> learningActivities,
    required List<LearningSummaryEntity> summaries,
    required List<LearningQuizEntity> quizzes,
    required List<LiveSessionEntity> liveSessions,
    required List<AssessmentQuestionEntity> assessmentQuestions,
  }) {
    return CourseEntity(
      id: id,
      title: title,
      description: description,
      objective: objective,
      learningOutcome: learningOutcome,
      coverImage: coverImage,
      urlLink: urlLink,
      isDisplayVideo: isDisplayVideo,
      videoUrl: videoUrl,
      categories: categories,
      downloadableOption: downloadableOption,
      courseLevel: courseLevel,
      courseType: courseType,
      isAllowFeedback: isAllowFeedback,
      isAllowDiscussion: isAllowDiscussion,
      discussion: discussion,
      acceptableScoreForAssignment: acceptableScoreForAssignment,
      acceptableScoreForAssessment: acceptableScoreForAssessment,
      estimatedDuration: estimatedDuration,
      numberOfEnrollments: numberOfEnrollments,
      totalLectures: totalLectures,
      totalQuizzes: totalQuizzes,
      viewCount: viewCount,
      rating: rating,
      createdBy: null,
      courseOrderType: courseOrderType,
      lectureOrderType: lectureOrderType,
      courseOrder: courseOrder,
      lectureOrderByLectureId: lectureOrderByLectureId,
      evaluationMessage: evaluationMessage,
      isXApiCourse: isXApiCourse,
      resourceFileUrl: resourceFileUrl,
      hasUserTakenCourse: hasUserTakenCourse,
      lectures: lectures,
      quizzes: quizzes,
      summaries: summaries,
      learningActivities: learningActivities,
      assessmentQuestions: assessmentQuestions,
      courseLearner: courseLearner,
      liveSessions: liveSessions,
      isUserCanAccessCourse: isUserCanAccessCourse,
      createdAt: createdAt,
    );
  }
}
