name: preferences
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

dependencies:
  base:
    path: ../base
  domain:
    path: ../domain

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.1
  mocktail: ^0.3.0
