include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - directives_ordering
    - prefer_relative_imports: true
    - avoid_print: true
    - prefer_single_quotes: true
    - avoid_dynamic_calls: true

analyzer:
  exclude: [commands.dart]