name: api
description: A starting point for Dart libraries or applications.
publish_to: none
version: 1.0.0
# repository: https://github.com/my_org/my_repo

scripts:
  build_runner_build: dart run build_runner build --delete-conflicting-outputs
  build_runner_watch: dart run build_runner watch --delete-conflicting-outputs

environment:
  sdk: '>=3.0.1 <4.0.0'

# Add regular dependencies here.
dependencies:
  dio: ^5.4.2+1
  base:
    path: ../../core/base
  domain:
    path: ../../core/domain
  preferences:
    path: ../../core/preferences
  json_annotation: ^4.9.0
  intl: ^0.19.0
  collection: ^1.17.1
  timezone: ^0.9.0

dev_dependencies:
  build_runner: ^2.4.11
  http_mock_adapter: ^0.4.4
  json_serializable: ^6.8.0
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.0