import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    blogPosts,
    blogPostQueries,
    blogPostComments,
    blogPostCategories,
    courseAssessmentQuestions,
    courseCategories,
    courses,
    courseLearners,
    offlineCourses,
    offlineCourseMedia,
    courseDownloadStatus,
    lectures,
    learningActivities,
    learningSummaries,
    learningQuizzes,
    userCourses,
    liveSessions,
  ];
  late final Shape0 blogPosts = Shape0(
      source: i0.VersionedTable(
        entityName: 'blog_posts',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
          _column_23,
          _column_24,
          _column_25,
          _column_26,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 blogPostQueries = Shape1(
      source: i0.VersionedTable(
        entityName: 'blog_post_queries',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY("query")',
        ],
        columns: [
          _column_28,
          _column_29,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 blogPostComments = Shape2(
      source: i0.VersionedTable(
        entityName: 'blog_post_comments',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_30,
          _column_31,
          _column_32,
          _column_24,
          _column_12,
          _column_33,
          _column_34,
          _column_18,
          _column_26,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 blogPostCategories = Shape3(
      source: i0.VersionedTable(
        entityName: 'blog_post_categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_35,
          _column_36,
          _column_37,
          _column_38,
          _column_26,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 courseAssessmentQuestions = Shape4(
      source: i0.VersionedTable(
        entityName: 'course_assessment_questions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_39,
          _column_40,
          _column_41,
          _column_42,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
          _column_26,
          _column_47,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 courseCategories = Shape5(
      source: i0.VersionedTable(
        entityName: 'course_categories',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_35,
          _column_26,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 courses = Shape6(
      source: i0.VersionedTable(
        entityName: 'courses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_2,
          _column_49,
          _column_50,
          _column_51,
          _column_52,
          _column_53,
          _column_14,
          _column_33,
          _column_22,
          _column_54,
          _column_55,
          _column_56,
          _column_57,
          _column_58,
          _column_59,
          _column_60,
          _column_61,
          _column_62,
          _column_63,
          _column_64,
          _column_65,
          _column_7,
          _column_66,
          _column_67,
          _column_68,
          _column_69,
          _column_70,
          _column_71,
          _column_72,
          _column_73,
          _column_74,
          _column_75,
          _column_76,
          _column_26,
          _column_47,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 courseLearners = Shape7(
      source: i0.VersionedTable(
        entityName: 'course_learners',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_39,
          _column_77,
          _column_78,
          _column_79,
          _column_80,
          _column_81,
          _column_82,
          _column_83,
          _column_84,
          _column_26,
          _column_47,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 offlineCourses = Shape8(
      source: i0.VersionedTable(
        entityName: 'offline_courses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(course_id)',
        ],
        columns: [
          _column_39,
          _column_26,
          _column_47,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 offlineCourseMedia = Shape9(
      source: i0.VersionedTable(
        entityName: 'offline_course_media',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(course_id, url)',
        ],
        columns: [
          _column_85,
          _column_39,
          _column_86,
          _column_2,
          _column_87,
          _column_26,
          _column_47,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 courseDownloadStatus = Shape10(
      source: i0.VersionedTable(
        entityName: 'course_download_status',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(course_id)',
        ],
        columns: [
          _column_39,
          _column_88,
          _column_89,
          _column_90,
          _column_26,
          _column_47,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape11 lectures = Shape11(
      source: i0.VersionedTable(
        entityName: 'lectures',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_2,
          _column_91,
          _column_49,
          _column_92,
          _column_33,
          _column_93,
          _column_39,
          _column_94,
          _column_95,
          _column_26,
          _column_47,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape12 learningActivities = Shape12(
      source: i0.VersionedTable(
        entityName: 'learning_activities',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_2,
          _column_49,
          _column_94,
          _column_39,
          _column_96,
          _column_95,
          _column_26,
          _column_47,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape12 learningSummaries = Shape12(
      source: i0.VersionedTable(
        entityName: 'learning_summaries',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_2,
          _column_49,
          _column_94,
          _column_96,
          _column_39,
          _column_95,
          _column_26,
          _column_47,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape13 learningQuizzes = Shape13(
      source: i0.VersionedTable(
        entityName: 'learning_quizzes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_2,
          _column_96,
          _column_39,
          _column_44,
          _column_97,
          _column_98,
          _column_26,
          _column_47,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape14 userCourses = Shape14(
      source: i0.VersionedTable(
        entityName: 'user_courses',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(course_id, learner_id)',
        ],
        columns: [
          _column_39,
          _column_99,
          _column_26,
          _column_47,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape15 liveSessions = Shape15(
      source: i0.VersionedTable(
        entityName: 'live_sessions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_0,
          _column_39,
          _column_96,
          _column_100,
          _column_101,
          _column_102,
          _column_103,
          _column_104,
          _column_105,
          _column_106,
          _column_49,
          _column_107,
          _column_78,
          _column_108,
          _column_109,
          _column_26,
          _column_47,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get slug =>
      columnsByName['slug']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bodyUpper =>
      columnsByName['body_upper']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get blockQuote =>
      columnsByName['block_quote']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bodyLower =>
      columnsByName['body_lower']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get privacy =>
      columnsByName['privacy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get viewCount =>
      columnsByName['view_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get shareCount =>
      columnsByName['share_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get shareLink =>
      columnsByName['share_link']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get duration =>
      columnsByName['duration']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get durationUnit =>
      columnsByName['duration_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imageUrl =>
      columnsByName['image_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get featuredVideo =>
      columnsByName['featured_video']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isDisplayVideo =>
      columnsByName['is_display_video']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get videoLink =>
      columnsByName['video_link']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get author =>
      columnsByName['author']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get hasRead =>
      columnsByName['has_read']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get numberOfReactions =>
      columnsByName['number_of_reactions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get numberOfComments =>
      columnsByName['number_of_comments']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get overallScore =>
      columnsByName['overall_score']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get hasQuiz =>
      columnsByName['has_quiz']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get categories =>
      columnsByName['categories']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tags =>
      columnsByName['tags']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currentReaction =>
      columnsByName['current_reaction']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get postReactions =>
      columnsByName['post_reactions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>('id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('slug', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>('title', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>('body_upper', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>('block_quote', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>('body_lower', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>('privacy', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>('view_count', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>('share_count', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>('share_link', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>('duration', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>('duration_unit', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>('image_url', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>('featured_video', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_14(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_display_video', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_display_video" IN (0, 1))'));
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>('video_link', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>('author', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_17(String aliasedName) =>
    i1.GeneratedColumn<bool>('has_read', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("has_read" IN (0, 1))'));
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>('number_of_reactions', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>('number_of_comments', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>('overall_score', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<bool> _column_21(String aliasedName) =>
    i1.GeneratedColumn<bool>('has_quiz', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("has_quiz" IN (0, 1))'));
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>('categories', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>('tags', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>('current_reaction', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>('post_reactions', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_26(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('created_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_27(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('updated_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime);

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get query =>
      columnsByName['query']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ids =>
      columnsByName['ids']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>('query', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>('ids', aliasedName, false,
        type: i1.DriftSqlType.string);

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get postId =>
      columnsByName['post_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get comment =>
      columnsByName['comment']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get user =>
      columnsByName['user']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currentReaction =>
      columnsByName['current_reaction']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imageUrl =>
      columnsByName['image_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get videoUrl =>
      columnsByName['video_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get replyCount =>
      columnsByName['reply_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get numberOfReactions =>
      columnsByName['number_of_reactions']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>('post_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>('comment', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>('user', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>('video_url', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>('reply_count', aliasedName, false,
        type: i1.DriftSqlType.int);

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get active =>
      columnsByName['active']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get numberOfArticles =>
      columnsByName['number_of_articles']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get numberOfPublicArticles =>
      columnsByName['number_of_public_articles']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_36(String aliasedName) =>
    i1.GeneratedColumn<bool>('active', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("active" IN (0, 1))'));
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>('number_of_articles', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>('number_of_public_articles', aliasedName, false,
        type: i1.DriftSqlType.int);

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get question =>
      columnsByName['question']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get options =>
      columnsByName['options']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get correctAnswers =>
      columnsByName['correct_answers']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get order =>
      columnsByName['order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get passingOption =>
      columnsByName['passing_option']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userAnswer =>
      columnsByName['user_answer']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>('course_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>('question', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>('options', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>('correct_answers', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>('order', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>('type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>('passing_option', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>('user_answer', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_47(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('updated_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_48(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('deleted_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get objective =>
      columnsByName['objective']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get learningOutcome =>
      columnsByName['learning_outcome']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverImage =>
      columnsByName['cover_image']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get urlLink =>
      columnsByName['url_link']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isDisplayVideo =>
      columnsByName['is_display_video']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get videoUrl =>
      columnsByName['video_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categories =>
      columnsByName['categories']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get downloadableOption =>
      columnsByName['downloadable_option']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get courseLevel =>
      columnsByName['course_level']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get courseType =>
      columnsByName['course_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isAllowFeedback =>
      columnsByName['is_allow_feedback']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get isAllowDiscussion =>
      columnsByName['is_allow_discussion']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get discussion =>
      columnsByName['discussion']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get acceptableScoreForAssignment =>
      columnsByName['acceptable_score_for_assignment']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get acceptableScoreForAssessment =>
      columnsByName['acceptable_score_for_assessment']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get estimatedDuration =>
      columnsByName['estimated_duration']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get numberOfEnrollments =>
      columnsByName['number_of_enrollments']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get totalLectures =>
      columnsByName['total_lectures']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get totalQuizzes =>
      columnsByName['total_quizzes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get viewCount =>
      columnsByName['view_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get courseOrderType =>
      columnsByName['course_order_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lectureOrderType =>
      columnsByName['lecture_order_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get courseOrder =>
      columnsByName['course_order']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lectureOrderByLectureId =>
      columnsByName['lecture_order_by_lecture_id']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get evaluationMessage =>
      columnsByName['evaluation_message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isXApiCourse =>
      columnsByName['is_x_api_course']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get resourceFileUrl =>
      columnsByName['resource_file_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get hasUserTakenCourse =>
      columnsByName['has_user_taken_course']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get isUserCanAccessCourse =>
      columnsByName['is_user_can_access_course']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get createdBy =>
      columnsByName['created_by']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>('description', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>('objective', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>('learning_outcome', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>('cover_image', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>('url_link', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>('downloadable_option', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>('course_level', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>('course_type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_57(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_allow_feedback', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_allow_feedback" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_58(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_allow_discussion', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_allow_discussion" IN (0, 1))'));
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>('discussion', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
        'acceptable_score_for_assignment', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>(
        'acceptable_score_for_assessment', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>('estimated_duration', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_63(String aliasedName) =>
    i1.GeneratedColumn<int>('number_of_enrollments', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>('total_lectures', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>('total_quizzes', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<double> _column_66(String aliasedName) =>
    i1.GeneratedColumn<double>('rating', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>('course_order_type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>('lecture_order_type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>('course_order', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
        'lecture_order_by_lecture_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>('evaluation_message', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_72(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_x_api_course', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_x_api_course" IN (0, 1))'));
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>('resource_file_url', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_74(String aliasedName) =>
    i1.GeneratedColumn<bool>('has_user_taken_course', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("has_user_taken_course" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_75(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_user_can_access_course', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_user_can_access_course" IN (0, 1))'));
i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>('created_by', aliasedName, true,
        type: i1.DriftSqlType.string);

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get percentage =>
      columnsByName['percentage']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get notifyCount =>
      columnsByName['notify_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get completionStatusByMaterialKey =>
      columnsByName['completion_status_by_material_key']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isReadyToEvaluate =>
      columnsByName['is_ready_to_evaluate']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get isReadyToGenerateCertificate =>
      columnsByName['is_ready_to_generate_certificate']!
          as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>('user_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_78(String aliasedName) =>
    i1.GeneratedColumn<String>('status', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_79(String aliasedName) =>
    i1.GeneratedColumn<int>('percentage', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_80(String aliasedName) =>
    i1.GeneratedColumn<int>('notify_count', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<bool> _column_81(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_active', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_active" IN (0, 1))'));
i1.GeneratedColumn<String> _column_82(String aliasedName) =>
    i1.GeneratedColumn<String>(
        'completion_status_by_material_key', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_83(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_ready_to_evaluate', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_ready_to_evaluate" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_84(
        String aliasedName) =>
    i1.GeneratedColumn<bool>(
        'is_ready_to_generate_certificate', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_ready_to_generate_certificate" IN (0, 1))'));

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbnail =>
      columnsByName['thumbnail']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_85(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        hasAutoIncrement: true,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('PRIMARY KEY AUTOINCREMENT'));
i1.GeneratedColumn<String> _column_86(String aliasedName) =>
    i1.GeneratedColumn<String>('url', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_87(String aliasedName) =>
    i1.GeneratedColumn<String>('thumbnail', aliasedName, true,
        type: i1.DriftSqlType.string);

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get downloadTaskId =>
      columnsByName['download_task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get downloadRecordJson =>
      columnsByName['download_record_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isHandled =>
      columnsByName['is_handled']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_88(String aliasedName) =>
    i1.GeneratedColumn<String>('download_task_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_89(String aliasedName) =>
    i1.GeneratedColumn<String>('download_record_json', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_90(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_handled', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_handled" IN (0, 1))'),
        defaultValue: const Constant(false));

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get resourceUrl =>
      columnsByName['resource_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get resourceType =>
      columnsByName['resource_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get videoUrl =>
      columnsByName['video_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get attachedFileUrl =>
      columnsByName['attached_file_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get media =>
      columnsByName['media']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get interactiveFeatures =>
      columnsByName['interactive_features']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_91(String aliasedName) =>
    i1.GeneratedColumn<String>('resource_url', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_92(String aliasedName) =>
    i1.GeneratedColumn<String>('resource_type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_93(String aliasedName) =>
    i1.GeneratedColumn<String>('attached_file_url', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_94(String aliasedName) =>
    i1.GeneratedColumn<String>('media', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_95(String aliasedName) =>
    i1.GeneratedColumn<String>('interactive_features', aliasedName, false,
        type: i1.DriftSqlType.string);

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get media =>
      columnsByName['media']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lectureId =>
      columnsByName['lecture_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get interactiveFeatures =>
      columnsByName['interactive_features']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_96(String aliasedName) =>
    i1.GeneratedColumn<String>('lecture_id', aliasedName, false,
        type: i1.DriftSqlType.string);

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lectureId =>
      columnsByName['lecture_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isTryAgain =>
      columnsByName['is_try_again']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get questions =>
      columnsByName['questions']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<bool> _column_97(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_try_again', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_try_again" IN (0, 1))'));
i1.GeneratedColumn<String> _column_98(String aliasedName) =>
    i1.GeneratedColumn<String>('questions', aliasedName, false,
        type: i1.DriftSqlType.string);

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get learnerId =>
      columnsByName['learner_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_99(String aliasedName) =>
    i1.GeneratedColumn<String>('learner_id', aliasedName, false,
        type: i1.DriftSqlType.string);

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get courseId =>
      columnsByName['course_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lectureId =>
      columnsByName['lecture_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get topic =>
      columnsByName['topic']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get meetingId =>
      columnsByName['meeting_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get startDateTime =>
      columnsByName['start_date_time']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get agenda =>
      columnsByName['agenda']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isHostVideoEnabled =>
      columnsByName['is_host_video_enabled']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get isParticipantVideoEnabled =>
      columnsByName['is_participant_video_enabled']!
          as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get durationInMinutes =>
      columnsByName['duration_in_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get passcode =>
      columnsByName['passcode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startUrl =>
      columnsByName['start_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get joinUrl =>
      columnsByName['join_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_100(String aliasedName) =>
    i1.GeneratedColumn<String>('topic', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_101(String aliasedName) =>
    i1.GeneratedColumn<String>('meeting_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_102(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('start_date_time', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<String> _column_103(String aliasedName) =>
    i1.GeneratedColumn<String>('agenda', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_104(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_host_video_enabled', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_host_video_enabled" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_105(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_participant_video_enabled', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_participant_video_enabled" IN (0, 1))'));
i1.GeneratedColumn<int> _column_106(String aliasedName) =>
    i1.GeneratedColumn<int>('duration_in_minutes', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_107(String aliasedName) =>
    i1.GeneratedColumn<String>('passcode', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_108(String aliasedName) =>
    i1.GeneratedColumn<String>('start_url', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_109(String aliasedName) =>
    i1.GeneratedColumn<String>('join_url', aliasedName, false,
        type: i1.DriftSqlType.string);
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
    ));
