name: messaging
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  transparent_image: ^2.0.1
  localization:
    path: ../../core/localization
  domain:
    path: ../../core/domain
  base:
    path: ../../core/base
  design_system:
    path: ../../core/design_system
  preferences:
    path: ../../core/preferences
  google_fonts: ^5.1.0
  assets:
    path: ../../core/assets
  intl: ^0.19.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^17.2.2
  rxdart: ^0.27.7
  go_router: ^14.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  mocktail: ^0.3.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
