name: base
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  collection: ^1.17.1
  equatable: ^2.0.5
  get_it: ^7.6.0
  logger: ^2.4.0
  email_validator: ^2.1.17

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
