name: design_system
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  transparent_image: ^2.0.1
  localization:
    path: ../../core/localization
  domain:
    path: ../../core/domain
  base:
    path: ../../core/base
  google_fonts: ^5.1.0
  assets:
    path: ../../core/assets
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  flutter_localizations:
    sdk: flutter
  flutter_svg_provider: ^1.0.6
  dropdown_button2: ^2.3.9
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.7
  smooth_page_indicator: ^1.1.0
  intl_phone_field: ^3.2.0
  animated_toggle_switch: ^0.8.2
  responsive_framework: ^1.4.0
  shimmer: ^3.0.0
  zoom_tap_animation: ^1.1.0
  youtube_player_flutter: ^9.0.3
  chewie: ^1.8.1
  video_player: ^2.8.6
  photo_view: ^0.15.0
  pinput: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.0.3
  flutter_widget_from_html_core: ^0.15.2
  url_launcher: ^6.2.6
  easy_pdf_viewer: ^1.0.8
  html: ^0.15.4
  flutter_inappwebview: ^6.1.2
  video_thumbnail:
    git:
      url: https://github.com/toe-lie/video_thumbnail.git
      ref: master
  path_provider: ^2.0.15

dependency_overrides:
  web: ^1.0.0

dev_dependencies:
  test: ^1.24.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2